


import { motion } from 'framer-motion';
import Link from 'next/link';
export default function companyProfile() {
  return (
    <main className="max-w-6xl mx-auto px-6 py-12 bg-white">
      <section className="prose max-w-none">
        <h1 className="font-bold">Company Profile</h1>
        <h2 className="font-semibold">Jilani Shipping International (JSI)</h2>


        <h2 className="font-semibold">Buyer’s Consolidation</h2>
        <h4 className="font-semibold">INTRODUCTION:</h4>
        <p>
          With latest developments in logistics industry, the scope of work for buyer’s consolidation does not remain limited to only consolidation of multiple LCL shipments from different suppliers to FCL for a specific buyer but to organize supply chain process in leaner and efficient manner along with maximum optimization of resources.
        </p>

        <h4 className="font-semibold">JSI's Strong Arm:</h4>
        <ul>
          <li>Security</li>
          <li>Installed with Fire Extinguishers</li>
          <li>Flexible working hours</li>
          <li>Warehouse Management System</li>
          <li>Bar Coding and Sticker printing</li>
          <li>Scanning &amp; System Uploading</li>
          <li>Buyers Consolidation</li>
          <li>Local deliveries</li>
          <li>Reporting &amp; Analysis</li>
          <li>Near to all industrial areas</li>
          <li>Easy access for all shipments coming from upcountry</li>
          <li>Within 5 Kms vicinity of Port Qasim</li>
        </ul>
        <p>
          This section presents the processes that take place in the current facility of JSI. Most of the time, goods are placed in the inventory before being redirected to the particular operation. The exception might be cross-docking and software updating. However, before that all the goods are unloaded from the truck and put to the buffer area where the process of receiving takes place. All received pallets are checked with the delivery list. Later on, the Software generates the in-house label with the unique barcode which contains the information about goods, their quantity, supplier and the end customer. Despite the fact that each pallet has been already labelled by the supplier, the new labels have to be printed in order to minimize the information included in the barcode and to be recognized by JSI Software.
        </p>

        <p>
          Further, the order message is generated and goods are relocated according to the information stated in the order. The message is given by the production leader and can be screened and followed on the tablet attached to every forklift in the warehouse. Workers can check which item should be moved from which location to which. The new location should be registered in the system.
        </p>

        <p>
          After the goods are subjected to the certain operation, e.g. repacking, in most cases they are transported to the shipping area where they are waiting to be loaded on the truck and sent to the customer. Sometimes, it might happen that goods go back to the inventory where they are stored until the transport order is generated by the customer.
        </p>

      </section>
    </main>
  );
}